<?php

namespace RedJasmine\AddressAdmin\Repositories;

use Dcat\Admin\Form;
use RedJasmine\Address\Models\Address as Model;
use Dcat\Admin\Repositories\EloquentRepository;
use RedJasmine\Admin\Facades\Admin;
use RedJasmine\Support\Helpers\User;

class Address extends EloquentRepository
{
    /**
     * Model.
     *
     * @var string
     */
    protected $eloquentClass = Model::class;

    public function store(Form $form)
    {

        $owner  =new User($form->input('owner_type'),$form->input('owner_uid')) ;

        return \RedJasmine\Address\Facades\Address::createForID($owner,$form->updates(),Admin::user());

        //return parent::store($form); // TODO: Change the autogenerated stub
    }

    public function update(Form $form)
    {

        return \RedJasmine\Address\Facades\Address::updateForID($form->model()->id,$form->updates(),Admin::user());
    }


}
