<?php

namespace RedJasmine\AddressAdmin\Repositories;

use Dcat\Admin\Form;
use RedJasmine\Address\Models\Address as Model;
use Dcat\Admin\Repositories\EloquentRepository;
use RedJasmine\Admin\Facades\Admin;
use RedJasmine\Support\Helpers\UserObjectBuilder;

class Address extends EloquentRepository
{
    /**
     * Model.
     *
     * @var string
     */
    protected $eloquentClass = Model::class;

    public function store(Form $form)
    {

        $user = [
            'type'     => $form->input('owner_type'),
            'uid'      => $form->input('owner_uid'),
            'nickname' => '',
            'avatar'   => '',
        ];
        $owner  = new UserObjectBuilder($user);


        return \RedJasmine\Address\Facades\Address::create($owner,$form->updates(),Admin::user());

        //return parent::store($form); // TODO: Change the autogenerated stub
    }

    public function update(Form $form)
    {

        return \RedJasmine\Address\Facades\Address::update($form->model()->id, $form->updates(), Admin::user());
    }


}
